ingress:
  enabled: true
  fqdn: "helm-v2-aws-example.test-cased-eks.preview-8.com"
  secretName: "helm-v2-aws-example-letsencrypt-production"
  annotations:
    # for aws deployments with ingress-nginx, cert-manager, and external-dns
    cert-manager.io/cluster-issuer: letsencrypt-production
    external-dns.alpha.kubernetes.io/hostname: helm-v2-aws-example.test-cased-eks.preview-8.com
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

postgresql:
  enabled: false
  auth:
    username: "cased"
    password: "casedshell"
    database: "cased"
  external:
    # only accessible via our VPC
    host: test-ci-db20221110151837801900000001.cjbhkdkvrpfq.us-west-2.rds.amazonaws.com
    port: 5432

config:
  objectStorageBackend: s3
  secret: v2
  log_level: info
  # Can switch back to release once a release containing https://github.com/cased/shell/pull/550 is pushed
  image: ghcr.io/cased/shell:unstable
  # Add some demo prompts
  jump: |
    queries:
    - provider: static
      prompt:
        featured: true
        hostname: aws-example-cased-shell-sshd
        username: app
        name: app server
        labels:
          app: cased-shell
    - provider: static
      prompt:
        featured: true
        hostname: aws-example-cased-shell-sshd
        username: app
        name: database server
        labels:
          app: cased-shell

server:
  enabled: true
  image: ghcr.io/cased/cased-server:main
  service:
    type: LoadBalancer
    loadBalancerClass: service.k8s.aws/nlb
    externalHostAndPort: a52bb642ce4e14edfb4e95ac7e67d0dc-120014874.us-west-2.elb.amazonaws.com:22
  tls:
    autoGenerated: true

sshd:
  image: ghcr.io/cased/sshd-demo:pr-633

aws:
  s3:
    bucket: test-cased-shell-ci
  region: us-west-2
  # These are set via `charts-install` and AWS_EXAMPLE_* Codespaces secrets
  # key:
  #   access:
  #   secret:
