# Set by chart-install if PR has 'docker:pr-image' label
# sshd:
#   image: "ghcr.io/cased/sshd-demo:pr-454"
# config:
#   image: "ghcr.io/cased/shell:pr-454"

config:
  log_level: debug

server:
  # Can be set to test PRs of cased/cased-server
  # image: ghcr.io/cased/cased-server:pr-8
  service:
    nodePort: 30022

ingress:
  # Set by charts-install
  # fqdn: ${CODESPACE_NAME}-8443.${GITHUB_CODESPACES_PORT_FORWARDING_DOMAIN}
  # Required due to Codespaces port-forwarding proxy behavior
  fqdnOverride: localhost
