version: '3.8'

services:
  app:
    entrypoint: []
    # Confirm that all supporting services come up healthy
    # TODO actually run a test here
    command:
      - docker
      - ps

  shell-postgres:
    image: postgres:11.6
    command: -p 5534
    restart: always
    network_mode: service:devcontainer
    volumes:
      - postgres-data-shell:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: cased
      POSTGRES_PASSWORD: shell
      POSTGRES_DB: cased-shell
