version: '3.9'

services:
  shell:
    image: ${REGISTRY}/shell:latest
    build:
      context: ..
      cache_from:
        - ${REGISTRY}/shell:latest
        - ghcr.io/cased/shell:main
        - ghcr.io/cased/shell-cache:main
      dockerfile: Dockerfile
  sshd-demo:
    image: ${REGISTRY}/sshd-demo:latest
    build:
      context: sshd
      cache_from:
        - ${REGISTRY}/sshd-demo:latest
        - ghcr.io/cased/sshd-demo:main
        - ghcr.io/cased/sshd-demo-cache:main
      dockerfile: Dockerfile
