{{- if eq .Values.config.objectStorageBackend "pvc" -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shell.fullname" . }}-pvc
  labels:
    {{- include "shell.labels" . | nindent 4 }}
data:
  STORAGE_BACKEND: local
  STORAGE_DIR: '.storage'
{{- end -}}
