apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shell.fullname" . }}-dex
  labels:
    {{- include "shell.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "files/dex.yaml").AsConfig | indent 2 }}
