apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shell.fullname" . }}-default-username
  labels:
    {{- include "shell.labels" . | nindent 4 }}
data:
    CASED_SHELL_SSH_USERNAME: '{{ .Values.config.CASED_SHELL_SSH_USERNAME }}'
