apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shell.fullname" . }}-scripts
  labels:
    {{- include "shell.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "*.sh").AsConfig | indent 2 }}
