apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shell.fullname" . }}-jwt
  labels:
    {{- include "shell.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_SIGNING_KEY: {{ .Values.config.key | b64enc | quote }}