apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shell.fullname" . }}-postgres
  labels:
    {{- include "shell.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  DATABASE_URL: {{ (printf "postgres://%s:%s@%s:%s/%s?connect_timeout=10&sslmode=%s"
      .Values.postgresql.auth.username
      .Values.postgresql.auth.password
      (include "postgresql.primary.fullname" .Subcharts.postgresql | trunc 63 | trimSuffix "-")
      (include "postgresql.service.port" .Subcharts.postgresql)
      .Values.postgresql.auth.database
      .Values.postgresql.sslMode) | b64enc | quote }}
  {{ else }}
  DATABASE_URL: {{ (printf "postgres://%s:%s@%s:%s/%s?connect_timeout=10&sslmode=%s"
      .Values.postgresql.auth.username
      .Values.postgresql.auth.password
      .Values.postgresql.external.host
      (.Values.postgresql.external.port | toString)
      .Values.postgresql.auth.database
      .Values.postgresql.sslMode) | b64enc | quote }}
  {{ end }}
  PGSSLMODE: {{ .Values.postgresql.sslMode | b64enc | quote }}
