{{- if eq .Values.config.objectStorageBackend "s3" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shell.fullname" . }}-s3
  labels:
    {{- include "shell.labels" . | nindent 4 }}
type: Opaque
data:
  STORAGE_BACKEND: {{ "s3" | b64enc | quote }}
  STORAGE_S3_REGION: {{ required ".Values.aws.region required!" .Values.aws.region | b64enc | quote }}
  STORAGE_S3_BUCKET: {{ required ".Values.aws.s3.bucket required!" .Values.aws.s3.bucket | b64enc | quote }}
  {{- with .Values.aws.key.access }}
  STORAGE_S3_ACCESS_KEY_ID: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.aws.key.secret }}
  STORAGE_S3_SECRET_ACCESS_KEY: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.aws.s3.endpoint }}
  STORAGE_S3_ENDPOINT: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.aws.s3.signatureVersion }}
  STORAGE_S3_SIGNATURE_VERSION: {{ . | b64enc | quote }}
  {{- end }}
{{- end -}}
