apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shell.fullname" . }}-sso
  labels:
    {{- include "shell.labels" . | nindent 4 }}
type: Opaque
data:
  SSO: 'true'

  # Okta OIDC
  {{- with .Values.config.sso.OKTA_OIDC_ISSUER }}
  OKTA_OIDC_ISSUER: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.OKTA_OIDC_CLIENT_ID }}
  OKTA_OIDC_CLIENT_ID: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.OKTA_OIDC_CLIENT_SECRET }}
  OKTA_OIDC_CLIENT_SECRET: {{ . | b64enc | quote }}
  {{- end }}

  # Okta SAML
  {{- with .Values.config.sso.OKTA_SAML_SSO_URL }}
  OKTA_SAML_SSO_URL: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.OKTA_SAML_ISSUER }}
  OKTA_SAML_ISSUER: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.OKTA_SAML_CA_CERT }}
  OKTA_SAML_CA_CERT: {{ . | b64enc | quote }}
  {{- end }}

  # GitHub
  {{- with .Values.config.sso.github_client_id }}
  OAUTH_GITHUB_CLIENT_ID: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.github_client_secret }}
  OAUTH_GITHUB_CLIENT_SECRET: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.github_orgs }}
  OAUTH_GITHUB_ORGS: {{ .name | b64enc | quote }}
  {{- with .teams }}
  OAUTH_GITHUB_TEAMS_{{ .name | upper | replace "-" "_" }}: {{ .teams | join "," | b64enc | quote }}
  {{- end }}
  {{- end }}

  # Google
  {{- with .Values.config.sso.google_client_id }}
  GOOGLE_OAUTH_CLIENT_ID: {{ . | b64enc | quote }}
  {{- end }}
  {{- with .Values.config.sso.google_client_secret }}
  GOOGLE_OAUTH_CLIENT_SECRET: {{ . | b64enc | quote }}
  {{- end }}
