{{- if .Values.server.enabled -}}
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    {{- include "shell.server.labels" . | nindent 4 }}
  name: {{ include "shell.fullname" . }}-cased-server
spec:
  ports:
  - name: api
    port: 6566
    targetPort: api
  selector:
    {{- include "shell.server.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{ end }}
