name: Test Charts - Required

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
    paths:
      - '.github/workflows/charts-lint-test.yml'
      - 'charts/**'
      - chart_schema.yaml
      - lintconf.yaml
      - ct.yaml

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    outputs:
       tests: ${{ steps.json.outputs.result }}
       changed: ${{ steps.list-changed.outputs.changed }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        helm_version:
          # oldest known supported
          - v3.10.1
          - latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ matrix.helm_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: List tests
        id: tests
        run: |
          set -x
          echo "ls=$(ls -1 charts/cased-shell/ci/ | sed 's/.yaml//' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Construct JSON Matrix
        id: json
        uses: actions/github-script@v6
        env:
          TESTS: ${{ steps.tests.outputs.ls }}
        with:
          script: |
            return process.env.TESTS.split(" ").filter(dir => dir.length > 0)

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          set -x
          changed=$(ct list-changed --config ct.yaml)
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

  test:
    runs-on: ubuntu-latest
    needs: lint
    if: needs.lint.outputs.changed == 'true'
    strategy:
      fail-fast: false
      matrix:
        test: ${{fromJson(needs.lint.outputs.tests)}}
        helm_version:
          # oldest known supported
          - v3.10.1
          - latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove tests other than ${{ matrix.test }}
        run: |
          for f in $(ls -1 charts/cased-shell/ci/ | grep -v ^${{ matrix.test }}.yaml); do
            rm -v charts/cased-shell/ci/$f
          done

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ matrix.helm_version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.x

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2

      - uses: debianmaster/actions-k3s@v1.0.5
        with:
          version: 'latest'

      # This optimization will work once a new release of chart-testing is cut
      # containing https://github.com/helm/chart-testing/pull/478
      - name: Modify chart-testing config for GitHub Actions
        run: |
          docker run -i --rm -v "${PWD}":/workdir -w /workdir mikefarah/yq:4 -P \
            ".skip-clean-up = true" \
            ct.yaml > ct-actions.yaml
            cat ct-actions.yaml

      - name: Run chart-testing (install)
        run: |
          if ! ct install --config ct-actions.yaml; then
            set -x
            kubectl get pods --all-namespaces
            kubectl get svc --all-namespaces
            kubectl get endpoints --all-namespaces
            exit 1
          fi

