name: Integration tests

on:
  push:

env:
  DATABASE_URL: postgres://cased:shell@127.0.0.1:5536/cased-shell-test
  DOCKER_BUILDKIT: "1"
  BUILDKIT_PROGRESS: "plain"

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: cased
          POSTGRES_PASSWORD: shell
          POSTGRES_DB: cased-shell-test
        ports:
          - 5536:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - run: ./test
