name: Integration tests

on:
  push:

env:
  DATABASE_URL: postgres://cased:shell@127.0.0.1:5536/cased-shell-test
  DOCKER_BUILDKIT: "1"
  BUILDKIT_PROGRESS: "plain"

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11.6
        env:
          POSTGRES_USER: cased
          POSTGRES_PASSWORD: shell
          POSTGRES_DB: cased-shell-test
        ports:
          - 5536:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: tmp/buildx
          key: ${{ runner.os }}-buildx-${{ github.ref }}
          restore-keys: |
            ${{ runner.os }}-buildx-${{ github.event.repository.default_branch }}

      - name: Expose GitHub Actions Cache env vars
        uses: crazy-max/ghaction-github-runtime@v2

      - run: ./test
        env:
          LOCAL_CACHE_TO: tmp/buildx-out

      - name: Move cache
        run: |
          rm -rf tmp/buildx
          if [ -d tmp/buildx-out ]; then
            mv tmp/buildx-out tmp/buildx
          fi